set(FREEMMS_BASEDIR_CORE ${CMAKE_SOURCE_DIR}/src/cli)

set(FREEMMS_CLI_MAIN_SOURCES
        ${FREEMMS_BASEDIR_CORE}/climain.cpp)


set(FREEMMS_CLI_MMS2PLAIN_SOURCES
        ${FREEMMS_CLI_MAIN_SOURCES}
        ${FREEMMS_BASEDIR_CORE}/mms2plain.cpp)


set(FREEMMS_CLI_PLAIN2MMS_SOURCES
        ${FREEMMS_CLI_MAIN_SOURCES}
        ${FREEMMS_BASEDIR_CORE}/pain2mms.cpp)

file(GLOB METADATA ${CMAKE_SOURCE_DIR}/src/core/metadata/*)
file(COPY ${METADATA} DESTINATION metadata)